#!/usr/bin/env node

/**
 * Retroactive AI-detection scan across the full article corpus
 * (Bucket C6 of v3 adoption).
 *
 * Walks `content/articles/*.mdx`, runs the Layer 1-5 scorer from
 * `check-article.ts` on each, and writes a sortable matrix at
 * `docs/audit/ai-detection-retroactive-20260428.md`. Articles scoring
 * composite >= 30 get flagged as rewrite candidates.
 *
 * Usage:
 *   npx tsx scripts/ai-detection/scan-corpus.ts
 *
 * Output:
 *   docs/audit/ai-detection-retroactive-20260428.md
 *   .tmp/ai-detection-retroactive.json (raw per-article)
 */

import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import { scoreArticle } from './check-article'

const ARTICLES_DIR = path.join(process.cwd(), 'content/articles')

interface RowSummary {
  slug: string
  category: string
  composite: number
  verdict: string
  dominantLayer: number
  l1: number
  l2: number
  l3: number
  l4: number
  l5: number
  l1Top: string[]
  l2Patterns: string[]
}

function main() {
  const files = fs
    .readdirSync(ARTICLES_DIR)
    .filter((f) => f.endsWith('.mdx') || f.endsWith('.md'))
    .sort()

  const rows: RowSummary[] = []
  const fullReports: Array<ReturnType<typeof scoreArticle> & { category: string }> = []

  for (const f of files) {
    const full = path.join(ARTICLES_DIR, f)
    const raw = fs.readFileSync(full, 'utf8')
    const data = matter(raw)
    const slug = f.replace(/\.mdx?$/, '')
    const category = (data.data.category as string) || 'unknown'
    const report = scoreArticle(slug, data.content)
    fullReports.push({ ...report, category })

    rows.push({
      slug,
      category,
      composite: report.composite,
      verdict: report.verdict,
      dominantLayer: report.dominantLayer,
      l1: report.layer1.score,
      l2: report.layer2.score,
      l3: report.layer3.score,
      l4: report.layer4.score,
      l5: report.layer5.score,
      l1Top: report.layer1.hits.slice(0, 3).map((h) => `${h.count}× ${h.phrase}`),
      l2Patterns: report.layer2.patterns.slice(0, 3),
    })
  }

  // Sort by composite descending so worst offenders surface at the top
  rows.sort((a, b) => b.composite - a.composite || a.slug.localeCompare(b.slug))

  // Distribution
  const dist = {
    ship: rows.filter((r) => r.composite <= 20).length,
    fix: rows.filter((r) => r.composite > 20 && r.composite <= 40).length,
    section: rows.filter((r) => r.composite > 40 && r.composite <= 70).length,
    full: rows.filter((r) => r.composite > 70).length,
  }
  const dominantCounts: Record<string, number> = { L1: 0, L2: 0, L3: 0, L4: 0, L5: 0 }
  for (const r of rows) dominantCounts[`L${r.dominantLayer}`]++

  // Write JSON
  const tmpDir = path.join(process.cwd(), '.tmp')
  if (!fs.existsSync(tmpDir)) fs.mkdirSync(tmpDir, { recursive: true })
  fs.writeFileSync(
    path.join(tmpDir, 'ai-detection-retroactive.json'),
    JSON.stringify({ scannedAt: '2026-04-28', count: rows.length, distribution: dist, dominantCounts, rows: fullReports }, null, 2),
  )

  // Write Markdown
  const lines: string[] = []
  lines.push('# AI-Detection Retroactive Scan — 2026-04-28')
  lines.push('')
  lines.push('Auto-generated by `scripts/ai-detection/scan-corpus.ts`. Layer thresholds use the literature-derived defaults from `docs/research/ai-detection-theory-20260428.md`. **Re-run after Bucket C3 baseline (`docs/research/human-baseline-20260428.json`) lands** for project-calibrated scoring.')
  lines.push('')
  lines.push('## Distribution')
  lines.push('')
  lines.push('| Verdict | Composite range | Count | % of corpus |')
  lines.push('| --- | --- | ---: | ---: |')
  const total = rows.length || 1
  lines.push(`| SHIP | 0-20 | ${dist.ship} | ${((dist.ship / total) * 100).toFixed(1)}% |`)
  lines.push(`| FIX_LAYER | 21-40 | ${dist.fix} | ${((dist.fix / total) * 100).toFixed(1)}% |`)
  lines.push(`| SECTION_REWRITE | 41-70 | ${dist.section} | ${((dist.section / total) * 100).toFixed(1)}% |`)
  lines.push(`| FULL_REWRITE | 71-100 | ${dist.full} | ${((dist.full / total) * 100).toFixed(1)}% |`)
  lines.push(`| **Total** | | **${rows.length}** | |`)
  lines.push('')
  lines.push('## Dominant-layer breakdown (which layer drove each composite)')
  lines.push('')
  lines.push('| Layer | Count | Layer name |')
  lines.push('| --- | ---: | --- |')
  lines.push(`| L1 | ${dominantCounts.L1} | phrase grep (banned phrases) |`)
  lines.push(`| L2 | ${dominantCounts.L2} | syntax patterns |`)
  lines.push(`| L3 | ${dominantCounts.L3} | sentence-length CV |`)
  lines.push(`| L4 | ${dominantCounts.L4} | MATTR + 4-gram repetition |`)
  lines.push(`| L5 | ${dominantCounts.L5} | burstiness + structural monotony |`)
  lines.push('')
  lines.push('## Per-article matrix (sorted by composite, worst first)')
  lines.push('')
  lines.push('| slug | cat | composite | verdict | dom | L1 | L2 | L3 | L4 | L5 | L1 hits | L2 patterns |')
  lines.push('| --- | --- | ---: | --- | :-: | ---: | ---: | ---: | ---: | ---: | --- | --- |')
  for (const r of rows) {
    const l1Cell = r.l1Top.join('; ') || ''
    const l2Cell = r.l2Patterns.join('; ') || ''
    lines.push(
      `| ${r.slug} | ${r.category} | ${r.composite} | ${r.verdict} | L${r.dominantLayer} | ${r.l1} | ${r.l2} | ${r.l3} | ${r.l4} | ${r.l5} | ${l1Cell} | ${l2Cell} |`,
    )
  }
  lines.push('')
  lines.push('## Rewrite candidates (composite >= 30)')
  lines.push('')
  const candidates = rows.filter((r) => r.composite >= 30)
  if (candidates.length === 0) {
    lines.push('(none)')
  } else {
    lines.push(`${candidates.length} of ${rows.length} articles flagged. Sort the matrix above to triage.`)
    lines.push('')
    for (const r of candidates) {
      const dominantLayerName = ['phrase grep', 'syntax patterns', 'sentence-length CV', 'MATTR/4-gram', 'burstiness/monotony'][r.dominantLayer - 1]
      lines.push(`- **${r.slug}** (${r.category}) — composite ${r.composite}, dominant L${r.dominantLayer} (${dominantLayerName}) — ${r.verdict}`)
    }
  }
  lines.push('')
  lines.push('## Caveats')
  lines.push('')
  lines.push('1. Statistical layer thresholds are provisional pending Bucket C3 (human baseline) calibration. Articles flagged at composite 30-50 may be false positives until the baseline lands.')
  lines.push('2. `composite = max(layers)` per skill design — a single severe fingerprint dominates. Cross-check the dominant layer before deciding rewrite.')
  lines.push('3. Quoted blocks (blockquote `>`, 「」, ASCII `"..."`) are stripped from input before scoring — but JSX components, MDX-embedded React, and frontmatter pass through gray-matter and are excluded automatically.')
  lines.push('4. L4 4-gram repetition is normalized per 1500 content tokens, so longer articles do not artificially inflate.')
  lines.push('5. Layer 6 (manual Opus read-through) is NOT included here — handled by `jpn-quality-reviewer` Skill, run separately.')
  lines.push('')

  const docPath = path.join(process.cwd(), 'docs/audit/ai-detection-retroactive-20260428.md')
  fs.writeFileSync(docPath, lines.join('\n'))

  console.log(`Retroactive scan complete: ${rows.length} articles.`)
  console.log(`Distribution: ${dist.ship} ship / ${dist.fix} fix-layer / ${dist.section} section-rewrite / ${dist.full} full-rewrite`)
  console.log(`Dominant: L1=${dominantCounts.L1} L2=${dominantCounts.L2} L3=${dominantCounts.L3} L4=${dominantCounts.L4} L5=${dominantCounts.L5}`)
  console.log(`Rewrite candidates (>=30): ${candidates.length}`)
  console.log(`Doc:  ${docPath}`)
  console.log(`JSON: .tmp/ai-detection-retroactive.json`)
}

main()
