import Image from 'next/image';
import { DEFAULT_BLUR_DATA_URL } from '@/lib/image-utils';
import imageManifest from '@/lib/image-manifest.json';

// Manifest is generated by `npm run images` and committed to git.
// Shape: { "/images/articles/foo/bar.jpg": { width: 1600, height: 1200 } }
const manifest = imageManifest as Record<string, { width: number; height: number }>;

interface MDXImageProps {
  src?: string;
  alt?: string;
  title?: string;
  width?: number;
  height?: number;
}

/**
 * Drop-in replacement for the bare `<img>` tag that next-mdx-remote produces
 * from `![alt](path)` markdown. Renders via `next/image` for WebP/AVIF
 * optimization, lazy loading, and CLS-safe width/height.
 *
 * Behaviour:
 * - If src starts with http(s)://: render as `unoptimized` external image with
 *   a 16:9 default. Cheap, no manifest entry needed.
 * - If src is in `lib/image-manifest.json`: use the recorded width/height.
 * - Otherwise: fall back to a plain `<img>` so the build never breaks if a
 *   new image is committed without re-running `npm run images`.
 */
export default function MDXImage({ src, alt, title, width, height }: MDXImageProps) {
  if (!src) return null;

  const altText = alt || '';
  const isExternal = /^https?:\/\//i.test(src);

  if (isExternal) {
    return (
      <Image
        src={src}
        alt={altText}
        title={title}
        width={width || 1600}
        height={height || 900}
        className="rounded-lg my-6 mx-auto"
        sizes="(max-width: 768px) 100vw, 760px"
        unoptimized
      />
    );
  }

  const entry = manifest[src];
  if (!entry) {
    // Unknown local image — render plain <img> with explicit dimensions if
    // they were passed, otherwise let the browser size it. Won't break the
    // build, but won't get next/image optimisation either.
    // eslint-disable-next-line @next/next/no-img-element
    return <img src={src} alt={altText} title={title} loading="lazy" className="rounded-lg my-6 mx-auto" />;
  }

  return (
    <Image
      src={src}
      alt={altText}
      title={title}
      width={width || entry.width}
      height={height || entry.height}
      className="rounded-lg my-6 mx-auto"
      sizes="(max-width: 768px) 100vw, 760px"
      placeholder="blur"
      blurDataURL={DEFAULT_BLUR_DATA_URL}
    />
  );
}
