"""Append web-verified events to data/events.json, skipping IDs already present."""
import json

NEW = [
    # From cakeswithfaces.co.uk/japan/pop-up-theme-cafes-japan/
    {
        "id": "doraemon-cafe-lish-2026",
        "ip": "Doraemon",
        "type": "collab-cafe",
        "title": "Doraemon Cafe at Cafe Lish",
        "venue": "Cafe Lish",
        "city": "Tokyo",
        "prefecture": "Tokyo",
        "startDate": "2026-03-01",
        "endDate": "2026-05-29",
        "thumbnail": "",
        "description": "Doraemon-themed collaboration cafe featuring Nobita and friends menu items, character desserts, and exclusive merchandise.",
        "reservation": "Advance reservation recommended",
        "tags": ["doraemon", "cafe-lish", "spring-2026"],
        "source": "https://dora-world.com/contents/4177",
        "officialUrl": "https://dora-world.com/contents/4177",
        "genre": "mixed",
        "badge": "hot",
        "lastVerified": "2026-04-15",
    },
    {
        "id": "goblin-gnome-horn-emo-harajuku-2026",
        "ip": "Goblin Gnome Horn",
        "type": "collab-cafe",
        "title": "Goblin Gnome Horn × Emo Cafe Harajuku",
        "venue": "Emo Cafe Harajuku",
        "city": "Tokyo",
        "prefecture": "Tokyo",
        "startDate": "2026-04-01",
        "endDate": "2026-04-15",
        "thumbnail": "",
        "description": "Limited-time Goblin Gnome Horn collaboration at Emo Cafe's Harajuku location with character-themed food and merchandise.",
        "reservation": "Walk-in or advance reservation",
        "tags": ["goblin-gnome-horn", "emo-cafe", "harajuku", "spring-2026"],
        "source": "https://emocafe.jp/collaboration/goblin_gnome_horn_osaka/",
        "officialUrl": "https://emocafe.jp/collaboration/goblin_gnome_horn_osaka/",
        "genre": "mixed",
        "badge": "limited",
        "lastVerified": "2026-04-15",
    },
    {
        "id": "goblin-gnome-horn-emo-osaka-2026",
        "ip": "Goblin Gnome Horn",
        "type": "collab-cafe",
        "title": "Goblin Gnome Horn × Emo Cafe Osaka",
        "venue": "Emo Cafe Osaka",
        "city": "Osaka",
        "prefecture": "Osaka",
        "startDate": "2026-04-22",
        "endDate": "2026-05-10",
        "thumbnail": "",
        "description": "Osaka leg of the Goblin Gnome Horn × Emo Cafe collaboration following the Harajuku run.",
        "reservation": "Walk-in or advance reservation",
        "tags": ["goblin-gnome-horn", "emo-cafe", "osaka", "spring-2026"],
        "source": "https://emocafe.jp/collaboration/goblin_gnome_horn_osaka/",
        "officialUrl": "https://emocafe.jp/collaboration/goblin_gnome_horn_osaka/",
        "genre": "mixed",
        "badge": "limited",
        "lastVerified": "2026-04-15",
    },
    {
        "id": "monsters-inc-ohmycafe-2026",
        "ip": "Monsters, Inc.",
        "type": "collab-cafe",
        "title": "Monsters, Inc. × OH MY CAFE Omotesando Hills",
        "venue": "OH MY CAFE Omotesando Hills",
        "city": "Tokyo",
        "prefecture": "Tokyo",
        "startDate": "2026-04-23",
        "endDate": "2026-06-28",
        "thumbnail": "",
        "description": "Pixar Monsters, Inc. collaboration cafe at OH MY CAFE. Sulley and Mike themed menu, scare-floor decor, and limited merchandise.",
        "reservation": "Online reservation via OH MY CAFE",
        "tags": ["monsters-inc", "pixar", "oh-my-cafe", "omotesando", "spring-2026"],
        "source": "https://monsters-ohmycafe.ltr-online.com/",
        "officialUrl": "https://monsters-ohmycafe.ltr-online.com/",
        "genre": "mixed",
        "badge": "hot",
        "lastVerified": "2026-04-15",
    },
    {
        "id": "magical-very-berry-hiromans-2026",
        "ip": "Magical Very Berry",
        "type": "collab-cafe",
        "title": "Magical Very Berry × Hiroman's Coffee",
        "venue": "Hiroman's Coffee Harajuku",
        "city": "Tokyo",
        "prefecture": "Tokyo",
        "startDate": "2026-04-01",
        "endDate": "2026-04-26",
        "thumbnail": "",
        "description": "Short-run Magical Very Berry collaboration at Hiroman's Coffee in Harajuku with themed drinks and pastries.",
        "reservation": "Walk-in",
        "tags": ["magical-very-berry", "hiromans-coffee", "harajuku", "spring-2026"],
        "source": "https://www.instagram.com/hiromans_coffee/",
        "officialUrl": "https://www.instagram.com/hiromans_coffee/",
        "genre": "shojo",
        "badge": "niche",
        "lastVerified": "2026-04-15",
    },
    {
        "id": "black-butler-tower-records-2026",
        "ip": "Black Butler",
        "type": "collab-cafe",
        "title": "Black Butler × Tower Records Cafe",
        "venue": "Tower Records Cafe Ikebukuro",
        "city": "Tokyo",
        "prefecture": "Tokyo",
        "startDate": "2026-03-20",
        "endDate": "2026-04-26",
        "thumbnail": "",
        "description": "Black Butler collaboration at Tower Records Cafe Ikebukuro with Sebastian- and Ciel-themed menu and exclusive fan goods.",
        "reservation": "Advance reservation via Tower Records",
        "tags": ["black-butler", "kuroshitsuji", "tower-records", "ikebukuro", "spring-2026"],
        "source": "https://tower.jp/article/news/2026/03/11/c101",
        "officialUrl": "https://tower.jp/article/news/2026/03/11/c101",
        "genre": "shojo",
        "badge": "ending-soon",
        "lastVerified": "2026-04-15",
    },
    {
        "id": "shugo-chara-tree-village-2026",
        "ip": "Shugo Chara!",
        "type": "collab-cafe",
        "title": "Shugo Chara! × Tree Village",
        "venue": "Tree Village (Tokyo, Yokohama, Osaka, Fukuoka)",
        "city": "Tokyo",
        "prefecture": "Tokyo",
        "startDate": "2026-04-23",
        "endDate": "2026-06-04",
        "thumbnail": "",
        "description": "Multi-city Shugo Chara! collaboration at Tree Village locations. Amu and the Guardian Characters themed menu with rotating merchandise.",
        "reservation": "Advance reservation",
        "tags": ["shugo-chara", "tree-village", "multi-city", "spring-2026"],
        "source": "https://tree-village.jp/news/014449.html",
        "officialUrl": "https://tree-village.jp/news/014449.html",
        "genre": "shojo",
        "badge": "niche",
        "lastVerified": "2026-04-15",
    },
    {
        "id": "chiras-art-oshiado-2026",
        "ip": "Chira's Art",
        "type": "collab-cafe",
        "title": "Chira's Art × Oshiado Harajuku",
        "venue": "Tea Specialty Shop Oshiado",
        "city": "Tokyo",
        "prefecture": "Tokyo",
        "startDate": "2026-04-24",
        "endDate": "2026-05-17",
        "thumbnail": "",
        "description": "Illustrator Chira's art collaboration at Oshiado's Harajuku tea specialty shop with themed beverages and original art goods.",
        "reservation": "Walk-in",
        "tags": ["chiras-art", "oshiado", "harajuku", "spring-2026"],
        "source": "https://oshiado.base.shop/",
        "officialUrl": "https://oshiado.base.shop/",
        "genre": "mixed",
        "badge": "niche",
        "lastVerified": "2026-04-15",
    },
    {
        "id": "golden-kamuy-tree-village-yokohama-2026",
        "ip": "Golden Kamuy",
        "type": "collab-cafe",
        "title": "Golden Kamuy × Tree Village Yokohama",
        "venue": "Tree Village Yokohama",
        "city": "Yokohama",
        "prefecture": "Kanagawa",
        "startDate": "2026-04-18",
        "endDate": "2026-05-15",
        "thumbnail": "",
        "description": "Golden Kamuy themed cafe featuring Hokkaido-inspired dishes, character drinks, and exclusive Sugimoto-squad merchandise.",
        "reservation": "Advance reservation",
        "tags": ["golden-kamuy", "tree-village", "yokohama", "spring-2026"],
        "source": "https://ofurocafe-utatane.com/16817",
        "officialUrl": "https://ofurocafe-utatane.com/16817",
        "genre": "seinen",
        "badge": "niche",
        "lastVerified": "2026-04-15",
    },
    {
        "id": "rilakkuma-camping-boxcafe-2026",
        "ip": "Rilakkuma",
        "type": "collab-cafe",
        "title": "Rilakkuma × BOX cafe&space (Camping Theme)",
        "venue": "BOX cafe&space SHIBUYA109 / Tennoji Mio / collabo index",
        "city": "Tokyo",
        "prefecture": "Tokyo",
        "startDate": "2026-04-23",
        "endDate": "2026-07-12",
        "thumbnail": "",
        "description": "Camping-themed Rilakkuma takeover of BOX cafe&space. Multi-city run across SHIBUYA109, Osaka Tennoji Mio, and Nagoya's collabo index.",
        "reservation": "Online booking via BOX cafe",
        "tags": ["rilakkuma", "box-cafe", "multi-city", "summer-2026", "camping"],
        "source": "https://rilakkuma-cafe-2026.ltr-online.com/",
        "officialUrl": "https://rilakkuma-cafe-2026.ltr-online.com/",
        "genre": "mixed",
        "badge": "hot",
        "lastVerified": "2026-04-15",
    },
    {
        "id": "sumikko-gurashi-athome-2026",
        "ip": "Sumikko Gurashi",
        "type": "collab-cafe",
        "title": "Sumikko Gurashi × @home cafe",
        "venue": "@home cafe Akihabara / Osaka",
        "city": "Tokyo",
        "prefecture": "Tokyo",
        "startDate": "2026-05-15",
        "endDate": "2026-09-14",
        "thumbnail": "",
        "description": "Long-run Sumikko Gurashi collaboration at @home maid cafe's Akihabara and Osaka branches. Kawaii omurice, themed parfaits, and photo spots.",
        "reservation": "Recommended for weekends",
        "tags": ["sumikko-gurashi", "at-home-cafe", "akihabara", "summer-2026"],
        "source": "https://cafe-athome.com/info/202077",
        "officialUrl": "https://cafe-athome.com/info/202077",
        "genre": "mixed",
        "badge": "hot",
        "lastVerified": "2026-04-15",
    },
    {
        "id": "ouran-my-charaful-osaka-2026",
        "ip": "Ouran High School Host Club",
        "type": "collab-cafe",
        "title": "Ouran High School Host Club × My Charaful Cafe (Osaka)",
        "venue": "My Charaful Cafe Osaka",
        "city": "Osaka",
        "prefecture": "Osaka",
        "startDate": "2026-04-22",
        "endDate": "2026-07-05",
        "thumbnail": "",
        "description": "Ouran Host Club 2nd-season collab at My Charaful Cafe Osaka. Tamaki, Kyoya, and the Host Club themed menu with exclusive merchandise.",
        "reservation": "Online booking recommended",
        "tags": ["ouran-host-club", "my-charaful", "osaka", "summer-2026"],
        "source": "https://ouran-2nd.hakusensha-cafe.com/",
        "officialUrl": "https://ouran-2nd.hakusensha-cafe.com/",
        "genre": "shojo",
        "badge": "niche",
        "lastVerified": "2026-04-15",
    },
    {
        "id": "ouran-motto-cafe-ikebukuro-2026",
        "ip": "Ouran High School Host Club",
        "type": "collab-cafe",
        "title": "Ouran High School Host Club × motto cafe Ikebukuro",
        "venue": "motto cafe Ikebukuro",
        "city": "Tokyo",
        "prefecture": "Tokyo",
        "startDate": "2026-03-06",
        "endDate": "2026-05-17",
        "thumbnail": "",
        "description": "Tokyo leg of the Ouran Host Club 2nd-season collaboration. Note: cafe is closed Apr 28–May 11 for menu changeover.",
        "reservation": "Online booking recommended",
        "tags": ["ouran-host-club", "motto-cafe", "ikebukuro", "spring-2026"],
        "source": "https://ouran-2nd.hakusensha-cafe.com/",
        "officialUrl": "https://ouran-2nd.hakusensha-cafe.com/",
        "genre": "shojo",
        "badge": "niche",
        "lastVerified": "2026-04-15",
    },
    {
        "id": "osomatsu-san-10th-ikebukuro-2026",
        "ip": "Osomatsu-san",
        "type": "collab-cafe",
        "title": "Osomatsu-san 10th Anniversary Cafe (Ikebukuro)",
        "venue": "SMILE BASE CAFE Ikebukuro",
        "city": "Tokyo",
        "prefecture": "Tokyo",
        "startDate": "2026-04-04",
        "endDate": "2026-04-20",
        "thumbnail": "",
        "description": "10th-anniversary Osomatsu-san cafe featuring the '10 Years of Love Omurice' and a Matsuno Brothers Bouquet Salad.",
        "reservation": "Advance reservation",
        "tags": ["osomatsu-san", "smile-base-cafe", "ikebukuro", "anniversary", "spring-2026"],
        "source": "https://essential-japan.com/events/osomatsu-san-10th-anniversary-cafe-in-tokyo-aichi-and-osaka-2026/",
        "officialUrl": "https://essential-japan.com/events/osomatsu-san-10th-anniversary-cafe-in-tokyo-aichi-and-osaka-2026/",
        "genre": "seinen",
        "badge": "niche",
        "lastVerified": "2026-04-15",
    },
    {
        "id": "osomatsu-san-10th-nagoya-2026",
        "ip": "Osomatsu-san",
        "type": "collab-cafe",
        "title": "Osomatsu-san 10th Anniversary Cafe (Nagoya)",
        "venue": "SMILE BASE CAFE Nagoya Sakae",
        "city": "Nagoya",
        "prefecture": "Aichi",
        "startDate": "2026-05-01",
        "endDate": "2026-05-11",
        "thumbnail": "",
        "description": "Final leg of the Osomatsu-san 10th anniversary tour at SMILE BASE CAFE Nagoya.",
        "reservation": "Advance reservation",
        "tags": ["osomatsu-san", "smile-base-cafe", "nagoya", "anniversary", "spring-2026"],
        "source": "https://essential-japan.com/events/osomatsu-san-10th-anniversary-cafe-in-tokyo-aichi-and-osaka-2026/",
        "officialUrl": "https://essential-japan.com/events/osomatsu-san-10th-anniversary-cafe-in-tokyo-aichi-and-osaka-2026/",
        "genre": "seinen",
        "badge": "limited",
        "lastVerified": "2026-04-15",
    },
    {
        "id": "pokemon-go-fest-2026",
        "ip": "Pokemon GO",
        "type": "event",
        "title": "Pokemon GO Fest 2026",
        "venue": "Tokyo Bay Area",
        "city": "Tokyo",
        "prefecture": "Tokyo",
        "startDate": "2026-05-29",
        "endDate": "2026-06-01",
        "thumbnail": "",
        "description": "Official Pokemon GO Fest outdoor event in the Tokyo Bay Area with exclusive raids, shiny spawns, and Japan-only features.",
        "reservation": "Ticketed event — buy via pokemongolive.com",
        "tags": ["pokemon", "pokemon-go", "tokyo-bay", "summer-2026", "outdoor"],
        "source": "https://pokemongolive.com/",
        "officialUrl": "https://pokemongolive.com/",
        "genre": "gaming",
        "badge": "hot",
        "lastVerified": "2026-04-15",
    },
    {
        "id": "taaf-2026-ikebukuro",
        "ip": "Tokyo Anime Award Festival",
        "type": "event",
        "title": "Tokyo Anime Award Festival (TAAF) 2026",
        "venue": "TOHO Cinemas Ikebukuro & Toshima Civic Center",
        "city": "Tokyo",
        "prefecture": "Tokyo",
        "startDate": "2026-03-13",
        "endDate": "2026-03-16",
        "thumbnail": "",
        "description": "Annual awards festival celebrating the best in Japanese animation with screenings, panels, and industry talks in Ikebukuro.",
        "reservation": "Ticketed screenings via official site",
        "tags": ["taaf", "awards", "ikebukuro", "spring-2026"],
        "source": "https://animefestival.jp/en/",
        "officialUrl": "https://animefestival.jp/en/",
        "genre": "mixed",
        "badge": "niche",
        "lastVerified": "2026-04-15",
    },
    {
        "id": "gakuen-idolmaster-animate-2026",
        "ip": "Gakuen Idolmaster",
        "type": "collab-cafe",
        "title": "Gakuen Idolmaster × Animate Cafe",
        "venue": "Animate Cafe Ikebukuro & Nagoya",
        "city": "Tokyo",
        "prefecture": "Tokyo",
        "startDate": "2026-04-02",
        "endDate": "2026-04-15",
        "thumbnail": "",
        "description": "Revival collaboration for the Gakuen Idolmaster mobile game at Animate Cafe. Character-themed Gratte drinks and icing cookies.",
        "reservation": "Animate Cafe advance ticket",
        "tags": ["gakuen-idolmaster", "animate-cafe", "ikebukuro", "nagoya", "spring-2026"],
        "source": "https://essential-japan.com/events/gakuen-idolmaster-collaboration-cafe-at-animate-cafe-2026/",
        "officialUrl": "https://essential-japan.com/events/gakuen-idolmaster-collaboration-cafe-at-animate-cafe-2026/",
        "genre": "gaming",
        "badge": "limited",
        "lastVerified": "2026-04-15",
    },
    {
        "id": "tokyo-revengers-natslive-toman-2026",
        "ip": "Tokyo Revengers",
        "type": "collab-cafe",
        "title": "Tokyo Revengers 'Toman Festival vol.5' × NATSLIVE Cafe",
        "venue": "NATSLIVE Cafe Tokyo / Osaka / Nagoya",
        "city": "Tokyo",
        "prefecture": "Tokyo",
        "startDate": "2026-06-06",
        "endDate": "2026-07-27",
        "thumbnail": "",
        "description": "Fifth 'Toman Festival' Tokyo Revengers collaboration at NATSLIVE Cafe with festival-style menu and character merch across three cities.",
        "reservation": "Advance reservation recommended",
        "tags": ["tokyo-revengers", "natslive", "multi-city", "summer-2026"],
        "source": "https://essential-japan.com/news/tokyo-revengers-cafe-opens-in-tokyo-osaka-and-nagoya-this-june/",
        "officialUrl": "https://essential-japan.com/news/tokyo-revengers-cafe-opens-in-tokyo-osaka-and-nagoya-this-june/",
        "genre": "shonen",
        "badge": "hot",
        "lastVerified": "2026-04-15",
    },
    {
        "id": "oshi-no-ko-s3-sweets-paradise-2026",
        "ip": "Oshi no Ko",
        "type": "collab-cafe",
        "title": "Oshi no Ko Season 3 × Sweets Paradise",
        "venue": "Sweets Paradise (Tokyo / Osaka / Kyoto + 3)",
        "city": "Tokyo",
        "prefecture": "Tokyo",
        "startDate": "2026-05-08",
        "endDate": "2026-06-30",
        "thumbnail": "",
        "description": "Oshi no Ko Season 3 buffet collaboration across six Sweets Paradise branches. B-Komachi themed desserts and savory plates.",
        "reservation": "Walk-in or online seat reservation",
        "tags": ["oshi-no-ko", "sweets-paradise", "multi-city", "summer-2026"],
        "source": "https://essential-japan.com/news/oshi-no-ko-collab-cafe-will-open-in-tokyo-osaka-and-nagoya-this-may/",
        "officialUrl": "https://essential-japan.com/news/oshi-no-ko-collab-cafe-will-open-in-tokyo-osaka-and-nagoya-this-may/",
        "genre": "seinen",
        "badge": "hot",
        "lastVerified": "2026-04-15",
    },
    {
        "id": "chainsaw-man-bomb-movie-2026",
        "ip": "Chainsaw Man",
        "type": "event",
        "title": "Chainsaw Man: The Bomb Devil Arc (Theatrical Release)",
        "venue": "Cinemas nationwide",
        "city": "Tokyo",
        "prefecture": "Tokyo",
        "startDate": "2026-07-03",
        "endDate": "2026-09-30",
        "thumbnail": "",
        "description": "Theatrical film adaptation of the Bomb Devil (Reze) arc. Expected tie-in cafes and merchandise pop-ups at major theater chains.",
        "reservation": "Theatre ticket via film site",
        "tags": ["chainsaw-man", "film", "mappa", "summer-2026"],
        "source": "https://chainsawman.dog/",
        "officialUrl": "https://chainsawman.dog/",
        "genre": "shonen",
        "badge": "hot",
        "lastVerified": "2026-04-15",
    },
]

with open('data/events.json', encoding='utf-8') as f:
    data = json.load(f)

existing_ids = {e['id'] for e in data['events']}
added = 0
skipped = 0
for ev in NEW:
    if ev['id'] in existing_ids:
        skipped += 1
        continue
    data['events'].append(ev)
    added += 1

data['lastUpdated'] = '2026-04-15'

with open('data/events.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
    f.write('\n')

print(f'Added {added} new events, skipped {skipped} duplicates. Total now {len(data["events"])}.')
